### ISSUE TITLE
Missing options on the check command nrpe

### ISSUE THREAD

**Issue by bortzmeyer** [Icinga/icinga2#4962]
Several useful options of the check_nrpe plugin are not available to Icinga 2 users, because they are not declared in the definition of the command. I specially miss -L (change the TLS cipher list) and the other crypto options.

**Comment by Crunsher** [comment]
You are welcome to submit a patch! ITL changes are easy to implement after reading the docs.

**Comment by dnsmichi** [comment]
Seems that this param was added in newer versions. Current version in Debian doesn't show it.

```
root@d9788b792b23:/# /usr/lib/nagios/plugins/check_nrpe --help

NRPE Plugin for Nagios
Copyright (c) 1999-2008 Ethan Galstad (nagios@nagios.org)
Version: 2.15
Last Modified: 09-06-2013
License: GPL v2 with exemptions (-l for more info)
SSL/TLS Available: Anonymous DH Mode, OpenSSL 0.9.6 or higher required

Usage: check_nrpe -H <host> [ -b <bindaddr> ] [-4] [-6] [-n] [-u] [-p <port>] [-t <timeout>] [-c <command>] [-a <arglist...>]

Options:
 -n         = Do no use SSL
 -u         = Make socket timeouts return an UNKNOWN state instead of CRITICAL
 <host>     = The address of the host running the NRPE daemon
 <bindaddr> = bind to local address
 -4         = user ipv4 only
 -6         = user ipv6 only
 [port]     = The port on which the daemon is running (default=5666)
 [timeout]  = Number of seconds before connection times out (default=10)
 [command]  = The name of the command that the remote daemon should run
 [arglist]  = Optional arguments that should be passed to the command.  Multiple
              arguments should be separated by a space.  If provided, this must be
              the last option supplied on the command line.

Note:
This plugin requires that you have the NRPE daemon running on the remote host.
You must also have configured the daemon to associate a specific plugin command
with the [command] option you are specifying here.  Upon receipt of the
[command] argument, the NRPE daemon will run the appropriate plugin command and
send the plugin output and return code back to *this* plugin.  This allows you
to execute plugins on remote hosts and 'fake' the results to make Nagios think
the plugin is being run locally.
```

**Comment by kobmaki** [comment]
The nrpe agent got a major update after more then three years (https://github.com/NagiosEnterprises/nrpe/blob/master/Changelog). It is now available as version 3 since july 2016. A lot of heavy security weakness were fixed. 

CentOS-6 and CentOS-7 do not include by default the nrpe package. It is provides by the epel repository. After enable the epel repo you can install the nrpe agent from the repo. The delivered agent is on version 2.15 from 09-06-2013. The same situation is with RH6 and RH7.

OpenSuse Tumbleweed provides by default the nrpe agent. The agent comes with the latest version 3.0 from 07-12-2016.

You have to look to the new security features in the README.SSL.md (https://github.com/NagiosEnterprises/nrpe/blob/master/README.SSL.md). 

To use the new options, the corresponding version must be installed on the icinga2 server.

Here are some (lot) detail information from the  OS, nrpe agent and the check_nrpe command. 

CentOS6
<pre>
[root@kob-cent6 ~]# cat /etc/centos-release 
CentOS release 6.8 (Final)
[root@kob-cent6 ~]# 
</pre>

<pre>
[root@kob-cent6 ~]# nrpe 

NRPE - Nagios Remote Plugin Executor
Copyright (c) 1999-2008 Ethan Galstad (nagios@nagios.org)
Version: 2.15
Last Modified: 09-06-2013
License: GPL v2 with exemptions (-l for more info)
SSL/TLS Available: Anonymous DH Mode, OpenSSL 0.9.6 or higher required
TCP Wrappers Available

***************************************************************
** POSSIBLE SECURITY RISK - COMMAND ARGUMENTS ARE SUPPORTED! **
**      Read the NRPE SECURITY file for more information     **
***************************************************************

Usage: nrpe [-n] -c <config_file> [-4|-6] <mode>

Options:
 -n            = Do not use SSL
 <config_file> = Name of config file to use
 -4            = use ipv4 only
 -6            = use ipv6 only
 <mode>        = One of the following operating modes:
   -i          =    Run as a service under inetd or xinetd
   -d          =    Run as a standalone daemon
   -d -s       =    Run as a subsystem under AIX

Notes:
This program is designed to process requests from the check_nrpe
plugin on the host(s) running Nagios.  It can run as a service
under inetd or xinetd (read the docs for info on this), or as a
standalone daemon. Once a request is received from an authorized
host, NRPE will execute the command/plugin (as defined in the
config file) and return the plugin output and return code to the
check_nrpe plugin.

[root@kob-cent6 ~]# 
</pre>

<pre>
[root@kob-cent6 ~]# /usr/lib64/nagios/plugins/check_nrpe
Incorrect command line arguments supplied

NRPE Plugin for Nagios
Copyright (c) 1999-2008 Ethan Galstad (nagios@nagios.org)
Version: 2.15
Last Modified: 09-06-2013
License: GPL v2 with exemptions (-l for more info)
SSL/TLS Available: Anonymous DH Mode, OpenSSL 0.9.6 or higher required

Usage: check_nrpe -H <host> [ -b <bindaddr> ] [-4] [-6] [-n] [-u] [-p <port>] [-t <timeout>] [-c <command>] [-a <arglist...>]

Options:
 -n         = Do no use SSL
 -u         = Make socket timeouts return an UNKNOWN state instead of CRITICAL
 <host>     = The address of the host running the NRPE daemon
 <bindaddr> = bind to local address
 -4         = user ipv4 only
 -6         = user ipv6 only
 [port]     = The port on which the daemon is running (default=5666)
 [timeout]  = Number of seconds before connection times out (default=10)
 [command]  = The name of the command that the remote daemon should run
 [arglist]  = Optional arguments that should be passed to the command.  Multiple
              arguments should be separated by a space.  If provided, this must be
              the last option supplied on the command line.

Note:
This plugin requires that you have the NRPE daemon running on the remote host.
You must also have configured the daemon to associate a specific plugin command
with the [command] option you are specifying here.  Upon receipt of the
[command] argument, the NRPE daemon will run the appropriate plugin command and
send the plugin output and return code back to *this* plugin.  This allows you
to execute plugins on remote hosts and 'fake' the results to make Nagios think
the plugin is being run locally.

[root@kob-cent6 ~]# 
</pre>

CentOS7
<pre>
[root@kob-cent7 ~]# cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

[root@kob-cent7 ~]# </pre>

<pre>
[root@kob-cent7 ~]# nrpe

NRPE - Nagios Remote Plugin Executor
Copyright (c) 1999-2008 Ethan Galstad (nagios@nagios.org)
Version: 2.15
Last Modified: 09-06-2013
License: GPL v2 with exemptions (-l for more info)
SSL/TLS Available: Anonymous DH Mode, OpenSSL 0.9.6 or higher required
TCP Wrappers Available

***************************************************************
** POSSIBLE SECURITY RISK - COMMAND ARGUMENTS ARE SUPPORTED! **
**      Read the NRPE SECURITY file for more information     **
***************************************************************

Usage: nrpe [-n] -c <config_file> [-4|-6] <mode>

Options:
 -n            = Do not use SSL
 <config_file> = Name of config file to use
 -4            = use ipv4 only
 -6            = use ipv6 only
 <mode>        = One of the following operating modes:
   -i          =    Run as a service under inetd or xinetd
   -d          =    Run as a standalone daemon
   -d -s       =    Run as a subsystem under AIX

Notes:
This program is designed to process requests from the check_nrpe
plugin on the host(s) running Nagios.  It can run as a service
under inetd or xinetd (read the docs for info on this), or as a
standalone daemon. Once a request is received from an authorized
host, NRPE will execute the command/plugin (as defined in the
config file) and return the plugin output and return code to the
check_nrpe plugin.

[root@kob-cent7 ~]# 
</pre>

<pre>
[root@kob-cent7 ~]# /usr/lib64/nagios/plugins/check_nrpe
Incorrect command line arguments supplied

NRPE Plugin for Nagios
Copyright (c) 1999-2008 Ethan Galstad (nagios@nagios.org)
Version: 2.15
Last Modified: 09-06-2013
License: GPL v2 with exemptions (-l for more info)
SSL/TLS Available: Anonymous DH Mode, OpenSSL 0.9.6 or higher required

Usage: check_nrpe -H <host> [ -b <bindaddr> ] [-4] [-6] [-n] [-u] [-p <port>] [-t <timeout>] [-c <command>] [-a <arglist...>]

Options:
 -n         = Do no use SSL
 -u         = Make socket timeouts return an UNKNOWN state instead of CRITICAL
 <host>     = The address of the host running the NRPE daemon
 <bindaddr> = bind to local address
 -4         = user ipv4 only
 -6         = user ipv6 only
 [port]     = The port on which the daemon is running (default=5666)
 [timeout]  = Number of seconds before connection times out (default=10)
 [command]  = The name of the command that the remote daemon should run
 [arglist]  = Optional arguments that should be passed to the command.  Multiple
              arguments should be separated by a space.  If provided, this must be
              the last option supplied on the command line.

Note:
This plugin requires that you have the NRPE daemon running on the remote host.
You must also have configured the daemon to associate a specific plugin command
with the [command] option you are specifying here.  Upon receipt of the
[command] argument, the NRPE daemon will run the appropriate plugin command and
send the plugin output and return code back to *this* plugin.  This allows you
to execute plugins on remote hosts and 'fake' the results to make Nagios think
the plugin is being run locally.

[root@kob-cent7 ~]# 
</pre>
OpenSuse thumbleweed
<pre>
kob-suse:~ # cat /etc/os-release 
NAME="openSUSE Tumbleweed"
# VERSION="20170302"
ID=opensuse
ID_LIKE="suse"
VERSION_ID="20170302"
PRETTY_NAME="openSUSE Tumbleweed"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:tumbleweed:20170302"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
kob-suse:~ #</pre>

<pre>
kob-suse:~ # nrpe 

NRPE - Nagios Remote Plugin Executor
Copyright (c) 1999-2008 Ethan Galstad (nagios@nagios.org)
Version: nrpe-3.0
Last Modified: 07-12-2016
License: GPL v2 with exemptions (-l for more info)
SSL/TLS Available, OpenSSL 0.9.6 or higher required
TCP Wrappers Available

***************************************************************
** POSSIBLE SECURITY RISK - COMMAND ARGUMENTS ARE SUPPORTED! **
**      Read the NRPE SECURITY file for more information     **
***************************************************************

Usage: nrpe [-n] -c <config_file> [-4|-6] <mode>

Options:
 -n, --no-ssl     = Do not use SSL
 -c <config_file> = Name of config file to use
 -4               = use ipv4 only
 -6               = use ipv6 only
 -h, --help       = Print this short help.
 -l,--license     = Print licensing information.
 <mode>           = One of the following operating modes:
   -i, --inetd    =    Run as a service under inetd or xinetd
   -d, --daemon   =    Run as a standalone daemon
   -d -s          =    Run as a subsystem under AIX
   -f             =    Don't fork() for systemd, launchd, etc.

Notes:
This program is designed to process requests from the check_nrpe
plugin on the host(s) running Nagios.  It can run as a service
under inetd or xinetd (read the docs for info on this), or as a
standalone daemon. Once a request is received from an authorized
host, NRPE will execute the command/plugin (as defined in the
config file) and return the plugin output and return code to the
check_nrpe plugin.

kob-suse:~ # </pre>

<pre>
kob-suse:~ # /usr/lib/nagios/plugins/check_nrpe
Incorrect command line arguments supplied

NRPE Plugin for Nagios
Copyright (c) 1999-2008 Ethan Galstad (nagios@nagios.org)
Version: nrpe-3.0
Last Modified: 07-12-2016
License: GPL v2 with exemptions (-l for more info)
SSL/TLS Available: OpenSSL 0.9.6 or higher required

Usage: check_nrpe -H <host> [-2] [-4] [-6] [-n] [-u] [-V] [-l] [-d <dhopt>]
       [-P <size>] [-S <ssl version>]  [-L <cipherlist>] [-C <clientcert>]
       [-K <key>] [-A <ca-certificate>] [-s <logopts>] [-b <bindaddr>]
       [-f <cfg-file>] [-p <port>] [-t <interval>:<state>]
       [-c <command>] [-a <arglist...>] [--help] [--license] [--no-ssl]

Options:
 <host>       = The address of the host running the NRPE daemon
 -2           = Only use Version 2 packets, not Version 3
 -4           = bind to ipv4 only
 -6           = bind to ipv6 only
 -n           = Do no use SSL
 -u           = (DEPRECATED) Make timeouts return UNKNOWN instead of CRITICAL
 -V           = Show version
 -l           = Show license
 <dhopt>      = Anonymous Diffie Hellman use:
                0 = Don't use Anonymous Diffie Hellman
                    (This will be the default in a future release.)
                1 = Allow Anonymous Diffie Hellman (default)
                2 = Force Anonymous Diffie Hellman
 <size>       = Specify non-default payload size for NSClient++
 <ssl ver>    = The SSL/TLS version to use. Can be any one of: SSLv2 (only),
                SSLv2+ (or above), SSLv3 (only), SSLv3+ (or above),
                TLSv1 (only), TLSv1+ (or above DEFAULT), TLSv1.1 (only),
                TLSv1.1+ (or above), TLSv1.2 (only), TLSv1.2+ (or above)
 <cipherlist> = The list of SSL ciphers to use (currently defaults
                to "ALL:!MD5:@STRENGTH". WILL change in a future release.)
 <clientcert> = The client certificate to use for PKI
 <key>        = The private key to use with the client certificate
 <ca-cert>    = The CA certificate to use for PKI
 <logopts>    = SSL Logging Options
 <bindaddr>   = bind to local address
 <cfg-file>   = configuration file to use
 [port]       = The port on which the daemon is running (default=5666)
 [command]    = The name of the command that the remote daemon should run
 [arglist]    = Optional arguments that should be passed to the command,
                separated by a space.  If provided, this must be the last
                option supplied on the command line.
 -h, --help   = Print this short help.
 -l,--license = Print licensing information.
 -n,--no-ssl  = Do not initial an ssl handshake with the server, talk in plaintext.

 NEW TIMEOUT SYNTAX
 -t <interval>:<state>
    <interval> = Number of seconds before connection times out (default=10)
    <state> = Check state to exit with in the event of a timeout (default=CRITICAL)
    Timeout state must be a valid state name (case-insensitive) or integer:
    (OK, WARNING, CRITICAL, UNKNOWN) or integer (0-3)

Note:
This plugin requires that you have the NRPE daemon running on the remote host.
You must also have configured the daemon to associate a specific plugin command
with the [command] option you are specifying here.  Upon receipt of the
[command] argument, the NRPE daemon will run the appropriate plugin command and
send the plugin output and return code back to *this* plugin.  This allows you
to execute plugins on remote hosts and 'fake' the results to make Nagios think
the plugin is being run locally.

kob-suse:~ #
</pre>

**Comment by menon0906** [comment]
How can I check the remote server disk space from Icinga2 ? I went through so many websites, it says via nrpe but there isn't any nrpe service available under /usr/lib64/nagios/plugins directory.

Can some one guide me to set up disk usage check for a remote hosts in Icinga2 ?

**Comment by dgoetz** [comment]
@menon0906: Please use community channels for such kind of questions like https://monitoring-portal.org/cms/ as this is clearly not an Icinga 2 issue. Also unrelated things in existing issues are not helpful. 
But to help you with your problem please read https://www.icinga.com/docs/icinga2/latest/doc/06-distributed-monitoring/ for use of Icinga 2 as agent and for legacy agents https://www.icinga.com/docs/icinga2/latest/doc/07-agent-based-monitoring/.

**Comment by dnsmichi** [comment]
@kobmaki thanks for the all the insights. I highly doubt that we can support all of them, nor do we endorse users to use the legacy NRPE clients. Obviously security was enhanced in NRPE 3.0, still not fixed entirely. Our focus is the Icinga 2 client.

If users need more options for their nrpe commands, they can for example manage a separate command which uses `import nrpe` and add the arguments depending on the Puppet facts they'll know from their clients. This goes far beyond the scope of the ITL though.
