### ISSUE TITLE
Misbehaving notification script can disrupt entire notification queue

### ISSUE THREAD

**Issue by yoshi314** [Icinga/icinga2#5402]
I added recently a growl notification script for a couple of services. However, doing so greatly reduced the amount of mail notifications going out to other users.

The excerpt of the log follows . 
```
`[2017-07-05 20:56:25 +0200] information/Notification: Sending reminder 'Problem' notification 'lubss055old!host-by-growl for user 'malistos'

[2017-07-05 20:56:25 +0200] information/Notification: Completed sending 'Problem' notification 'lubss055old!host-by-growl' for checkable 'lubss055old' and user 'malistos'.

[2017-07-05 20:56:25 +0200] information/Notification: Sending reminder 'Problem' notification 'lubss055old!host-by-growl for user 'baduda'

[2017-07-05 20:56:25 +0200] information/Notification: Completed sending 'Problem' notification 'lubss055old!host-by-growl' for checkable 'lubss055old' and user 'baduda'.

[2017-07-05 20:56:25 +0200] information/Notification: Sending reminder 'Problem' notification 'lubss055old!host-by-growl for user 'm15kowal'

[2017-07-05 20:56:25 +0200] information/Notification: Completed sending 'Problem' notification 'lubss055old!host-by-growl' for checkable 'lubss055old' and user 'm15kowal'.

[2017-07-05 20:56:25 +0200] warning/PluginNotificationTask: Notification command for object 'lubss055old' (PID: 18776, arguments: '/etc/icinga2/scripts/growl-host-notification.sh') terminated with exit code 255, output: A password is required at /usr/local/share/perl/5.20.2/Net/Growl.pm line 28.

[2017-07-05 20:56:25 +0200] warning/PluginNotificationTask: Notification command for object 'lubss055old' (PID: 18777, arguments: '/etc/icinga2/scripts/growl-host-notification.sh') terminated with exit code 255, output: A password is required at /usr/local/share/perl/5.20.2/Net/Growl.pm line 28.

[2017-07-05 20:56:30 +0200] information/Notification: Sending reminder 'Problem' notification 'lubss055old!host-by-mail for user 'malistos'

[2017-07-05 20:56:30 +0200] information/Notification: Sending reminder 'Problem' notification 'lubss055old!host-by-mail for user 'baduda'

[2017-07-05 20:56:30 +0200] information/Notification: Sending reminder 'Problem' notification 'lubss055old!host-by-mail for user 'm15kowal'

[2017-07-05 20:56:30 +0200] information/Notification: Completed sending 'Problem' notification 'lubss055old!host-by-mail' for checkable 'lubss055old' and user 'malistos'.

[2017-07-05 20:56:30 +0200] information/Notification: Completed sending 'Problem' notification 'lubss055old!host-by-mail' for checkable 'lubss055old' and user 'm15kowal'.

[2017-07-05 20:56:30 +0200] information/Notification: Completed sending 'Problem' notification 'lubss055old!host-by-mail' for checkable 'lubss055old' and user 'baduda'.

[2017-07-05 21:56:30 +0200] information/Notification: Sending reminder 'Problem' notification 'lubss055old!host-by-mail for user 'malistos'

[2017-07-05 21:56:30 +0200] information/Notification: Sending reminder 'Problem' notification 'lubss055old!host-by-mail for user 'baduda'

[2017-07-05 21:56:30 +0200] information/Notification: Sending reminder 'Problem' notification 'lubss055old!host-by-mail for user 'm15kowal'

[2017-07-05 21:56:30 +0200] information/Notification: Completed sending 'Problem' notification 'lubss055old!host-by-mail' for checkable 'lubss055old' and user 'malistos'.

[2017-07-05 21:56:30 +0200] information/Notification: Completed sending 'Problem' notification 'lubss055old!host-by-mail' for checkable 'lubss055old' and user 'm15kowal'.

[2017-07-05 21:56:30 +0200] information/Notification: Completed sending 'Problem' notification 'lubss055old!host-by-mail' for checkable 'lubss055old' and user 'baduda'.

[2017-07-05 22:56:31 +0200] information/Notification: Sending reminder 'Problem' notification 'lubss055old!host-by-mail for user 'malistos'

[2017-07-05 22:56:31 +0200] information/Notification: Completed sending 'Problem' notification 'lubss055old!host-by-mail' for checkable 'lubss055old' and user 'malistos'.

[2017-07-05 22:56:31 +0200] information/Notification: Sending reminder 'Problem' notification 'lubss055old!host-by-mail for user 'baduda'

[2017-07-05 22:56:31 +0200] information/Notification: Sending reminder 'Problem' notification 'lubss055old!host-by-mail for user 'm15kowal'

[2017-07-05 22:56:31 +0200] information/Notification: Completed sending 'Problem' notification 'lubss055old!host-by-mail' for checkable 'lubss055old' and user 'baduda'.

[2017-07-05 22:56:31 +0200] information/Notification: Completed sending 'Problem' notification 'lubss055old!host-by-mail' for checkable 'lubss055old' and user 'm15kowal'.

[2017-07-05 23:56:33 +0200] information/Notification: Sending reminder 'Problem' notification 'lubss055old!host-by-mail for user 'malistos'

[2017-07-05 23:56:33 +0200] information/Notification: Sending reminder 'Problem' notification 'lubss055old!host-by-mail for user 'baduda'

[2017-07-05 23:56:33 +0200] information/Notification: Sending reminder 'Problem' notification 'lubss055old!host-by-mail for user 'm15kowal'`

```

The thing is, the notification ought to go out to at least ~15 users, which are assigned as a usergroup. Instead, mail notifications went to 3 people, even though it's the growl notification that exhibited the problem.

It seems that if growl notification failed, icinga2 would not send ANY notifications to subsequent users. The user 'baduda' has no growl credentials, hence the message for password.

**Comment by yoshi314** [comment]
The mail notification is defined as follows: 

`Object 'lubss055old!host-by-mail' of type 'Notification':
  % declared in '/etc/icinga2/zones.d/global/notification/powiadomienia-pocztowe.conf', lines 1:0-1:40
  * __name = "lubss055old!host-by-mail"
  * command = "mail-host-notification"
    % = modified in '/etc/icinga2/zones.d/global/notification/template/mail-host-notification.conf', lines 10:3-10:36
  * command_endpoint = ""
  * host_name = "lubss055old"
    % = modified in '/etc/icinga2/zones.d/global/notification/powiadomienia-pocztowe.conf', lines 1:0-1:40
  * interval = 3600
    % = modified in '/etc/icinga2/zones.d/global/notification/template/generic-host-notification.conf', lines 4:3-4:16
  * name = "host-by-mail"
  * package = "_etc"
    % = modified in '/etc/icinga2/zones.d/global/notification/powiadomienia-pocztowe.conf', lines 1:0-1:40
  * period = "24x7"
    % = modified in '/etc/icinga2/zones.d/global/notification/template/mail-host-notification.conf', lines 7:3-7:17
  * service_name = ""
  * states = [ "Up", "Down" ]
    % = modified in '/etc/icinga2/zones.d/global/notification/template/mail-host-notification.conf', lines 12:3-12:23
  * templates = [ "host-by-mail", "mail-host-notification", "generic-host-notification-email", "generic-host-notification" ]
    % = modified in '/etc/icinga2/zones.d/global/notification/powiadomienia-pocztowe.conf', lines 1:0-1:40
    % = modified in '/etc/icinga2/zones.d/global/notification/template/mail-host-notification.conf', lines 6:1-6:46
    % = modified in '/etc/icinga2/zones.d/global/notification/template/generic-host-notification-email.conf', lines 1:0-1:54
    % = modified in '/etc/icinga2/zones.d/global/notification/template/generic-host-notification.conf', lines 1:0-1:48
  * times
    % = modified in '/etc/icinga2/zones.d/global/notification/template/generic-host-notification.conf', lines 18:5-18:41
    * begin = 30
  * type = "Notification"
  * types = [ "Problem", "Acknowledgement", "Recovery", "Custom", "FlappingStart", "FlappingEnd", "DowntimeStart", "DowntimeEnd", "DowntimeRemoved" ]
    % = modified in '/etc/icinga2/zones.d/global/notification/template/mail-host-notification.conf', lines 13:3-15:57
  * user_groups = [ "linux-admins" ]
    % = modified in '/etc/icinga2/zones.d/global/notification/template/generic-host-notification.conf', lines 5:3-5:34
  * users = [ "cc-developers", "ce_dev" ]
    % = modified in '/etc/icinga2/zones.d/global/notification/template/generic-host-notification-email.conf', lines 17:5-17:52
  * vars = null
  * zone = "ABS"
    % = modified in '/etc/icinga2/zones.d/global/notification/powiadomienia-pocztowe.conf', lines 1:0-1:40
`

Where linux-admins is at least 20 people.

**Comment by Crunsher** [comment]
Hi,

could you add your Icinga 2 version (I assume its 2.6.3 but let's make sure) and your Notification config?

**Comment by yoshi314** [comment]
Icinga2 is r2.6.3-1 , packaged for Debian.

As for notification config, i am not sure what exactly do you need.

**Comment by Crunsher** [comment]
Overlooked your first comment :/ I'll just assume you are not doing anything funny with your growl object and try to reproduce this.

**Comment by yoshi314** [comment]
It can be reproduced with just email notification - i had it happen before i introduced growl to the mix. 

Define user with no email, and assign email notification to everyone. Make sure the email command exits with an error if no email is specificed (default mail notification script should be ok). 

I think in that case icinga2 simply crashed, but that might have been fixed by now.

**Comment by Crunsher** [comment]
I tried to reproduce this with a group with 100 users, the notification would only write a line in a file and then fail. But despite all of them failing instantly (log had failure messages and sending notification messages mixed) all of the notifications were sent. 

As I was unable to reproduce this, I'm going to close this.
If the Problem persists in 2.8.0 (release sometime next week), please update this ticket or create a new one referencing this.

**Comment by yoshi314** [comment]
I am hitting this again on current icinga2. Namely, certain users are not receving their sms notifications, and i have no clue why. I have logging enabled in my sms script and simply no sms messages got sent for a few issues during the last couple of days.

It seems that the notification queue cuts out abruptly and there is no error message in the log.

**Comment by Crunsher** [comment]
I'll try again to reproduce this later, I should still have the setup lying around somewhere. Hopefully it works this time

**Comment by yoshi314** [comment]
I think it was a misconfiguration in my case. I'll get back to this issue when i am 100% certain i have a reproducible case.

**Comment by dnsmichi** [comment]
Notification scripts are just run and their return code is logged. They don't skip/stop additional users waiting for their notification, the call is asynchronous. If you have a reliable test case to reproduce the problem, we can re-open this issue.
